version: "3.4"

services:
  frontend:
    image: frontend
    container_name: frontend
    user: root
    volumes:
      - ../data/logs/nginx:/logs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      api_gateway:
        condition: service_started
